### ISSUE TITLE
Add commit and push

### ISSUE THREAD

**Issue by aripollak** [rtyley/agit#57]
I realize this is probably already the number one feature request, but I didn't see it in the issue tracker :)

**Comment by williamlagos** [comment]
Yes, this is the most important feature to add in AGit at this moment.

**Comment by AfzalivE** [comment]
hey, what's holding up this feature? maybe I can help.

**Comment by williamlagos** [comment]
We need the commit and push actions to AGit, so we can work on the smartphone and/or tablet with this. I appreciate your help.

**Comment by AfzalivE** [comment]
I know, that's what I'm asking. what's stopping the developers from implementing this?

**Comment by williamlagos** [comment]
I really don't know, maybe they're busy in solving another issues on AGit.

**Comment by RaD** [comment]
My app is needed pull/push intents to communicate with GitHub. I need push feature a lot.

**Comment by edburns** [comment]
I cannor justify the cost for this app until this feature exists.

**Comment by gergelypolonkai** [comment]
I would also be grateful for this feature, as it would turn my phone/tablet into a whole development environment. If you need any help like research or some code, ask and I'm sure some of us will be happy to help!

**Comment by BeekeeperAlex** [comment]
Count me in on wanting this feature. When I downloaded the app I assumed it was a full-featured git client. I was disappointed when I found out it was read-only. I got my money refunded from the app store but will gladly return when commit and push are added :)

**Comment by daniellandau** [comment]
The original author writes on the front page, that commit/push isn't implemented, because merging isn't, but I'd be happy to have even basic fast-forward support.

**Comment by Vanuan** [comment]
I think the show stopper is the UI. As I understand AGit uses JGit which has commit, merge and push support.
For pushing you'll need pull supporl (unless you want to force push which is pointless)
But how UI would look like for merging? It would be straightforward if there's no conflict, but what if there is?

In my view, making commit functionality without merge would make AGit unusable even for read only, since you won't be able to pull recent changes without deleting the repo, that in turn will make commit functionallity useless.

So, it's like chicken and egg problem: to make push you'll need merge (resolve conflict) first. To test merge you'll need commit. The solution is to implement them both, which requires enormous effort.
