### ISSUE TITLE
Support multiple file explorer 

### ISSUE THREAD

**Issue by anpieber** [rtyley/agit#75]
It would be pretty nice if alternative file managers, beside oi file manager, could be used. E.g. File expert would be nice :-)

**Comment by rtyley** [comment]
Hi @anpieber - Agit integrates with file manager apps by invoking the open-standard `PICK_DIRECTORY` intent, as you can see in the source for Agit here:

https://github.com/rtyley/agit/blob/645dc322/agit/src/main/java/com/madgag/agit/DashboardActivity.java#L63..L69

The PICK_DIRECTORY intent is a very simple intent defined by the OpenIntents group:

http://www.openintents.org/en/node/165 - `org.openintents.action.PICK_DIRECTORY`
http://www.openintents.org/en/node/164 - `org.openintents.action.PICK_FILE`

Unfortunately, at the moment, the OI File Manager is the only app I'm aware of that supports any kind of external invocation by intent _at all_ - which is crazy. For instance, I've asked the developers of the otherwise excellent [Folders by SAS](https://play.google.com/store/apps/details?id=com.sas.android.folders) app to support this intent, without success.

[File Expert](https://play.google.com/store/apps/details?id=xcxin.filexpert) also looks like a great app but so far as I can tell it doesn't support the `org.openintents.action.PICK_DIRECTORY` intent either. If you're a paying customer, you might want to get in touch with them and ask them to add support for this intent. Once that's added, Agit will automatically integrate with File Expert too. If you have any success in getting them to update the product, let me know with a comment on this ticket, I'll test the ticket and add a recommendation for the app.

There's nothing more Agit can do to support alternative file managers at this time, so closing this ticket for now.

**Comment by anpieber** [comment]
Thank you very much for the fast feedback. I've filed a feature request at "File Expert" and keep you up to date about their response.
